##
## Build
##

FROM golang:1.16-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /process_exporter

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /process_exporter /process_exporter
COPY --from=build /usr/bin/lsof /usr/bin/lsof

EXPOSE 8080

CMD [ "/process_exporter" ]