apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring.svc:8080",
                "version": 1
            }
        ]
    }
  dashboards.yml: |+
    apiVersion: 1
    providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/custom-dashboard.json
  custom-dashboard.json: |+
    {
    "annotations": {
        "list": [
        {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
            "limit": 100,
            "matchAny": false,
            "tags": [],
            "type": "dashboard"
            },
            "type": "dashboard"
        }
        ]
    },
    "editable": true,
    "gnetId": null,
    "graphTooltip": 0,
    "iteration": 1629561048633,
    "links": [],
    "panels": [
        {
        "datasource": "prometheus",
        "fieldConfig": {
            "defaults": {
            "color": {
                "mode": "palette-classic"
            },
            "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                "legend": false,
                "tooltip": false,
                "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                "group": "A",
                "mode": "none"
                },
                "thresholdsStyle": {
                "mode": "off"
                }
            },
            "mappings": [],
            "thresholds": {
                "mode": "absolute",
                "steps": [
                {
                    "color": "green",
                    "value": null
                },
                {
                    "color": "red",
                    "value": 80
                }
                ]
            }
            },
            "overrides": []
        },
        "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 0
        },
        "id": 2,
        "options": {
            "legend": {
            "calcs": [],
            "displayMode": "list",
            "placement": "bottom"
            },
            "tooltip": {
            "mode": "single"
            }
        },
        "targets": [
            {
            "exemplar": true,
            "expr": "listening_processes_count{job=\"process-exporter\",node=~\"$instance\"}",
            "interval": "",
            "legendFormat": "{{ node }}",
            "queryType": "randomWalk",
            "refId": "A"
            }
        ],
        "title": "Listening Process Count",
        "type": "timeseries"
        }
    ],
    "schemaVersion": 30,
    "style": "dark",
    "tags": [],
    "templating": {
        "list": [
        {
            "allValue": null,
            "current": {
            "selected": false,
            "text": [
                "gke-promdemo-pool-2-63d16d4a-cxxq"
            ],
            "value": [
                "gke-promdemo-pool-2-63d16d4a-cxxq"
            ]
            },
            "datasource": "prometheus",
            "definition": "label_values(listening_processes_count{job=\"process-exporter\"},node)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": false,
            "label": "Node",
            "multi": true,
            "name": "instance",
            "options": [],
            "query": {
            "query": "label_values(listening_processes_count{job=\"process-exporter\"},node)",
            "refId": "StandardVariableQuery"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
        }
        ]
    },
    "time": {
        "from": "now-30m",
        "to": "now"
    },
    "timepicker": {},
    "timezone": "",
    "title": "Listening Process Dashboard",
    "uid": "U4PCAP7nz",
    "version": 1
    }