apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "500M"
            cpu: "500m"
          requests: 
            memory: 250M
            cpu: "250m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasource-volume
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-dashboard-volume
            readOnly: false
          - mountPath: /var/lib/grafana/dashboards/
            name: grafana-dashboard
            readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasource-volume
          configMap:
              defaultMode: 420
              name: grafana-config
              items:
              - key: prometheus.yaml
                path: prometheus.yml
        - name: grafana-dashboard-volume
          configMap:
              defaultMode: 420
              name: grafana-config
              items:
              - key: dashboards.yml
                path: dashboards.yml
        - name: grafana-dashboard
          configMap:
              defaultMode: 420
              name: grafana-config
              items:
              - key: custom-dashboard.json
                path: custom-dashboard.json