kind: Service
apiVersion: v1
metadata:
  name: process-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8080'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: process-exporter
  ports:
  - name: process-exporter
    protocol: TCP
    port: 8080
    targetPort: 8080